environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

    - PYTHON:  "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.2"
      PYthON_ARCH: "32"

    - PYTHON:  "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.2"
      PYTHON_ARCH: "64"

  install:
    # Install dependencies
    - "%PYTHON%/python.exe C:/get-pip.py"
    - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

build: false # not needed ror Python

test_script:
    - "%CMD_IN_ENV% py.test"

    
