version: '{build}'
environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"

init:
  - git config --global core.autocrlf input

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get_pip.py')
  - "%PYTHON%/python.exe C:/get-pip.py"
  - "%PYTHON$/Scripts/pip.exe install --upgrade setuptools"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

build: False

test_script:
  - "py.test"

