..  |ACC|           replace:: Austin Community College
..  _ACC:           http://www.austincc.edu/
..  |IE|            replace:: Internet Explorer
..  |WE|            replace:: Windows Explorer
..  |VL|            replace:: VisualLogic
..  _VL:            http://www.visuallogic.org
..  |VB|            replace:: VirtualBox
..  _VB:            https://www.virtualbox.org/
..  |WWW|           replace:: World-Wide-Web
..  |RST|           replace:: reStructuredText

..  _ACM:           http://www.acm.org
..  _Adafruit:      http://www.adafruit.com/
..  _Amazon:        https://aws.amazon.com/
..  _Ansible:       http://www.ansible.com/home
..  _Apache:        http://httpd.apache.org/
..  _Arduino:       http://www.arduino.cc/
..  _ATXhackerspace: http://atxhs.org/wiki/Main_Page
..  _BibTeX:        http://www.bibtex.org/
..  _Catch:         https://github.com/philsquared/Catch
..  _Chef:          https://www.chef.io/
..  _`Course Technology`:   http://solutions.cengage.com/brands/course-technology/
..  _`coveralls.io`: https://coveralls.io/
..  _CSS3:          http://www.w3schools.com/css/css3_intro.asp
..  _docutils:      http://docutils.sourceforge.net/
..  _DropBox:       https://www.dropbox.com
..  _DynDNS:        http://dyndns.com/
..  _Facebook:      https://www.facebook.com/
..	_gas:			https://sourceware.org/binutils/docs/as/
..  _GDB:           http://www.gnu.org/software/gdb/
..  _Git:           http://git-scm.com/
..  _GitLab:        https://about.gitlab.com/
..  _GitHub:        https://github.com/
..  _GitWeb:        http://git-scm.com/docs/gitweb.html
..  _Gitorial:      https://github.com/jpetazzo/gitorial
..  _GitPython:     https://pypi.python.org/pypi/GitPython/
..  _GLUT:          https://www.opengl.org/resources/libraries/glut/
..  _gMail:         http://www.gmail.com/
..  _Gnu:           https://www.gnu.org/
..  _Gravatar:      https://en.gravatar.com/
..  _gVim:          http://www.vim.org/
..  _Homebrew:      http://brew.sh/
..  _HTML5:         http://www.w3schools.com/html/html5_intro.asp
..  _`Ian Bicking`: http://www.ianbicking.org/
..  _LinkedIn:      https://www.linkedin.com/
..  _LaTeX:         http://www.latex-project.org/
..  _MacTeX:        https://tug.org/mactex/
..  _MacVim:        https://code.google.com/p/macvim/
..  _MikTeX:        http://miktex.org/
..  _MinGW:         http://mingw-w64.sourceforge.net/
..  _Nasm:          http://nasm.us/
..  _Oracle:        http://www.oracle.com/index.html
..  _OpenGL:        https://www.opengl.org/
..  _PastBin:       http://pastebin.com/
..  _Pololu:        http://www.pololu.com/
..  _Puppet:        http://puppetlabs.com/
..  _PyGame:        http://www.pygame.org/news.html
..  _Python:        https://www.python.org/
..  _Rackspace:     http://www.rackspace.com/
..  _reStructuredText:  http://docutils.sourceforge.net/rst.html
..  _Ruby:          https://www.ruby-lang.org/en/
..  _Subversion:    https://subversion.apache.org/
..  _Sphinx:        http://sphinx-doc.org/
..  _Sphinx-Tut:    https://pypi.python.org/pypi/tut
..  _SWIG:          http://www.swig.org/
..  _Teensy:        http://www.pjrc.com/
..  _TeX:           http://tug.org/
..  _Trac:          http://trac.edgewall.org/
..  _TravisCI:      https://travis-ci.org/ 
..  _Ubuntu:        http://www.ubuntu.com/
..  _Vim:           http://www.vim.org/
..  _Vagrant:       https://www.vagrantup.com/
..  _virtualenv:    https://pypi.python.org/pypi/virtualenv
..  _VMWare:        http://www.vmware.com/
..  _YAML:          http://yaml.org/

..  _AgnerFog:      http://www.agner.org/optimize/
..  _Teensy2:       http://www.pjrc.com
..  _Arduino:       http://www.arduino.cc/
..  _Atmel:         http://www.atmel.com
..  _Microchip:     http://www.microchip.com/

